### PR TITLE
Exposed DataType properties

### PR DESCRIPTION
**Pull request by dularish**
This is to make it possible to read unknown structs of compound data

### CODE REVIEW

**Comment by Apollo3zehn** [comment]
Sorry I have not seen your question regarding the pull request in issue #15 . Thank you for your PR and the sample code. I am reluctant to make all internals public until I am sure that there is no other way. Please give me some time to evaluate it, I just became a new father and have now even less time than before. I will come back to the PR but I cannot guarantee you that this will be soon. I guess it will take a while until I find the time to work again on HDF5.NET (I will do it definitely, but now other projects are more urgent unfortunately :-/). My plan is to have a first release end of this year.

**Comment by dularish** [comment]
Yes, sure, do take your time. I've also tried to minimally expose types.

We see better performance, ease of use with HDF.NET, and we would love to have this change to make it possible for us to fetch all data.

Congratulations on becoming father.

**Comment by dularish** [comment]
Hello,

Would like to just check with you if you have made any decision already regarding this pull request.

**Comment by Apollo3zehn** [comment]
Hi, 
sorry I am currently busy with reparing another project and when that works again, I continue with HDF5.NET. I would first like to test my idea to implement the ExpandoObject approach. If that does not work for your use case I will review your PR. I would like to decouple internal and external API, so probably, I will build a clean interface to expose the data type properties. The problem is that the internal type system is quite large because the HDF5 spec evolved over time which led to different data type message versions. I prefer to abstract away the history and provide a clean API.  

Sorry for the delay :(

**Comment by dularish** [comment]
Hello,

I thought I could check with you if you have implemented any solution for this problem. Do you have any timeframe in mind to either get my solution implemented or Expando approach?

**Comment by Apollo3zehn** [comment]
I have made significant progress in another project but it took much longer than expected. I will work on in for another few weeks and then I'll hopefully have time for this project again. I really want to get a 1.0 release ready as soon as possible.

**Comment by dularish** [comment]
Thank you for your update. Meanwhile, we are thinking to publish our forked version as a NuGet package for usage in our commercial product, until a feature comes from yourself.

Our forked version with source code in github.com would still carry the same license, but our product would not. 

We find all these aspects in accordance with the GNU LESSER GENERAL PUBLIC LICENSE. Do you think it is okay that we go ahead with it? Should we do something special for usage in our product?

Thank you.

**Comment by Apollo3zehn** [comment]
Its fine for me, I will probably switch to MIT license anyway. Please go ahead.

**Comment by dularish** [comment]
Hello,
I hope this is my last query here. Do you have any timeline in mind regarding switching to MIT license?

**Comment by Apollo3zehn** [comment]
It's done :-)

**Comment by Apollo3zehn** [comment]
v1.0.0-alpha.9 now supports reading unknown structs (https://github.com/Apollo3zehn/HDF5.NET#63-unknown-structs). Data type properties are not publicly accessible yet but I will try to find a solution tomorrow to allow alternative methods of reading unknown structs.

**Comment by Apollo3zehn** [comment]
The `H5DataType` class now has one property per data class exposed (https://github.com/Apollo3zehn/HDF5.NET/commit/fe52c2bfd796abae429bbb81b6351091e06adaab#diff-454a66032d9b09cbbdedc8f19fd83fd7f9108b4062085cd381b688fd566941cf) in version `1.0.0-alpha.20`.

Most of these are still useless since I am still reluctant to expose everything. But from my point of view the most important information is the `Array` base type and the list of `Compound` members which in turn provides the member `Name`, `Offset` and `Type`. Examples:

```cs
var firstMemberName = dataset.Type.Compound.Members[0].Name;
var arrayBaseType = dataset.Type.Array.BaseType;
```

I`ll close your PR for now. Sorry that it took so long to make the required changes. If you need more internal data exposed than is available now, please create a new issue.

**Pull request closed without merging**
